name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
      - name: Using github action checkout marketplace
        uses: actions/checkout@v2
        

      - name: Running a Custom Script
        run: echo Hello Priyanshu
