name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
      - name: Using github action checkout marketplace
        uses: actions/checkout@v2
        

      - name: Running a Custom Script
        run: echo Hello Priyanshu

# Make sure your script is executable (if it's a Bash script)
      - name: Make script executable
        run: chmod +x ./install.sh

      # Run the custom script located at the root of the repository
      - name: Run custom script
        run: ./install.sh

      - name: Run docker ps commands
        run: sudo docker ps
